# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Media_final_project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FBSDKLoginKit'

  # Pods for Media_final_project

  target 'Media_final_projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Media_final_projectUITests' do
    # Pods for testing
  end

end
